version: "3.9"
services:
  web:
    build:
      context: .
      args:
        - CI_SHA1=${CIRCLE_SHA1}
    ports:
      - "3030:3030"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: "redis:alpine"
