# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_and_deploy:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Build image
          command: docker build --build-arg CI_SHA1=$CIRCLE_SHA1 -t rs-test/web .
      - run:
          name: Deploy image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_APP} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_APP} web

workflows:
  version: 2.1
  build_image:
    jobs:
      - build_and_deploy